#!/bin/bash

frames=8

for size in mdpi:48 hdpi:72 xhdpi:96 xxhdpi:144 xxxhdpi:192; do
    IFS=: read size_name icon_size <<<$size
    (( corner_size = icon_size / 10, rect_size = icon_size * 4 / 5, rect_end = icon_size * 9 / 10, centre = icon_size / 2 ))
    for frame in $(eval "echo {1..$frames}"); do
	(( lrpos = corner_size + frame * rect_size / frames ))
	gm convert -size ${icon_size}x${icon_size} xc:transparent -stroke white -fill transparent -draw "roundrectangle $corner_size,$corner_size $rect_end,$rect_end $corner_size,$corner_size" -fill white -draw "roundrectangle $corner_size,$corner_size $lrpos,$rect_end $corner_size,$corner_size" drawable-${size_name}/ic_left_right_${frame}.png
	gm convert -size ${icon_size}x${icon_size} xc:transparent -stroke white -fill transparent -draw "roundrectangle $corner_size,$corner_size $rect_end,$rect_end $corner_size,$corner_size" -fill white -draw "roundrectangle $corner_size,$corner_size $rect_end,$lrpos $corner_size,$corner_size" drawable-${size_name}/ic_top_down_${frame}.png
	(( rlpos = corner_size + (frames - frame) * rect_size / frames ))
	gm convert -size ${icon_size}x${icon_size} xc:transparent -stroke white -fill transparent -draw "roundrectangle $corner_size,$corner_size $rect_end,$rect_end $corner_size,$corner_size" -fill white -draw "roundrectangle $rlpos,$corner_size $rect_end,$rect_end $corner_size,$corner_size" drawable-${size_name}/ic_right_left_${frame}.png
	gm convert -size ${icon_size}x${icon_size} xc:transparent -stroke white -fill transparent -draw "roundrectangle $corner_size,$corner_size $rect_end,$rect_end $corner_size,$corner_size" -fill white -draw "roundrectangle $corner_size,$rlpos $rect_end,$rect_end $corner_size,$corner_size" drawable-${size_name}/ic_bottom_up_${frame}.png
	(( centre_edge_out = centre - ( rect_size / 2 * frame / frames ) ))
	gm convert -size ${icon_size}x${icon_size} xc:transparent -stroke white -fill transparent -draw "roundrectangle $corner_size,$corner_size $rect_end,$rect_end $corner_size,$corner_size" -fill white -draw "circle $centre,$centre, $centre, $centre_edge_out" drawable-${size_name}/ic_centre_out_${frame}.png
	(( stroke_width = rect_size / 2 * frame / frames,
	   centre_edge_in_half = corner_size + stroke_width / 2 ))
	echo rect_size $rect_size stroke_width $stroke_width centre_edge_in_half $centre_edge_in_half
	gm convert -size ${icon_size}x${icon_size} xc:transparent -fill transparent -stroke white -draw "roundrectangle $corner_size,$corner_size $rect_end,$rect_end $corner_size,$corner_size" -strokewidth $stroke_width -draw "circle $centre,$centre $centre,$centre_edge_in_half" drawable-${size_name}/ic_centre_in_${frame}.png
    done
done
